In [9]:
import torch
a = torch.arange(12).reshape(3,4)
b = a.clone()
b is a
b

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
b.sum(axis=1,keepdims=True),b.sum(axis=0)

(tensor([[ 6],
         [22],
         [38]]),
 tensor([12, 15, 18, 21]))

In [25]:
import torch
a = torch.arange(4)
b =torch.arange(8).reshape(2,4)
a,b,torch.mv(b,a)

(tensor([0, 1, 2, 3]),
 tensor([[0, 1, 2, 3],
         [4, 5, 6, 7]]),
 tensor([14, 38]))

In [26]:
a = torch.arange(4).reshape(2,2)
b = a.clone()
torch.dot(a,b)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors