In [2]:
import torch 
a = torch.tensor([0,2])
b = torch.tensor([[0.1,0.2,0.6],
                   [0.5,0.8,0.9]])

b = b.argmax(axis=1)
cmp = b.type(a.dtype) == a
cmp

for a ,b in zip([0.0,0.0],(1,2)):
    print(a,b)
print(*zip([0.0,0.0],(1,2)))

[a + float(b) for a ,b in zip([0.0,0.0],(1,2))]


0.0 1
0.0 2
(0.0, 1) (0.0, 2)


[1.0, 2.0]

In [3]:
x = torch.tensor([[1,2,-1],[1,-1,3]])
b = torch.zeros_like(x)
x,b

(tensor([[ 1,  2, -1],
         [ 1, -1,  3]]),
 tensor([[0, 0, 0],
         [0, 0, 0]]))

In [4]:
torch.max(x,b)

tensor([[1, 2, 0],
        [1, 0, 3]])

In [9]:
import torch 
x  = torch.tensor(range(10))
y = torch.rand(x.shape)
x,y

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([0.8698, 0.6429, 0.5326, 0.4241, 0.1123, 0.1499, 0.8812, 0.3577, 0.6891,
         0.2017]))

In [12]:
dropout = 0.2
z = (y>dropout).float()
z,z*x/(1-dropout)

(tensor([1., 1., 1., 1., 0., 0., 1., 1., 1., 1.]),
 tensor([ 0.0000,  1.2500,  2.5000,  3.7500,  0.0000,  0.0000,  7.5000,  8.7500,
         10.0000, 11.2500]))

In [32]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [34]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [38]:
y = torch.dot(x,x)
z = x*x
y,z

(tensor(14., grad_fn=<DotBackward0>),
 tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>))

In [39]:
y.backward()
x.grad

tensor([0., 2., 4., 6.])

In [40]:
w = x.sum()
w

tensor(6., grad_fn=<SumBackward0>)

In [47]:
x.grad.zero_()
w.backward()
x.grad

tensor([1., 1., 1., 1.])

In [48]:
x.grad.zero_()
z.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [22]:
import torch

x = torch.tensor(range(27),dtype=torch.float).reshape(3,3,3)
y = torch.ones(2,3,1,1,dtype=torch.float)
x,y,y.shape

(tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.]],
 
         [[ 9., 10., 11.],
          [12., 13., 14.],
          [15., 16., 17.]],
 
         [[18., 19., 20.],
          [21., 22., 23.],
          [24., 25., 26.]]]),
 tensor([[[[1.]],
 
          [[1.]],
 
          [[1.]]],
 
 
         [[[1.]],
 
          [[1.]],
 
          [[1.]]]]),
 torch.Size([2, 3, 1, 1]))

In [23]:
x = x.view(3,9)
y = y.view(2,3)
x,y

(tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12., 13., 14., 15., 16., 17.],
         [18., 19., 20., 21., 22., 23., 24., 25., 26.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [24]:
y@x

tensor([[27., 30., 33., 36., 39., 42., 45., 48., 51.],
        [27., 30., 33., 36., 39., 42., 45., 48., 51.]])