In [1]:
import torch
from torch import nn

In [ ]:
#X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
#K = torch.tensor([[0.0, 1.0], [2.0, 3.0]])

In [9]:
def corr2d(X,K):
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
    return Y

In [ ]:
#corr2d(X,K)

In [27]:
conv2d = nn.Conv2d(1,1,kernel_size=(1,2),bias=False)
"""
Conv2d结构
class Conv2d(nn.Module):
    def __init(self,kernel_size):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(kernel_size))
        self.bias = nn.Parameter(torch.zeros(1))

    def forward(x):
        return 
"""
x = torch.ones(6,8)
x[:,2:6] = 0
k = torch.tensor([[1.0,-1.0]])
y = corr2d(x,k)
x,k,y

(tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
         [1., 1., 0., 0., 0., 0., 1., 1.],
         [1., 1., 0., 0., 0., 0., 1., 1.],
         [1., 1., 0., 0., 0., 0., 1., 1.],
         [1., 1., 0., 0., 0., 0., 1., 1.],
         [1., 1., 0., 0., 0., 0., 1., 1.]]),
 tensor([[ 1., -1.]]),
 tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
         [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
         [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
         [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
         [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
         [ 0.,  1.,  0.,  0.,  0., -1.,  0.]]))

In [29]:
epoch = 10
x = x.reshape((1, 1, 6, 8))
y = y.reshape((1, 1, 6, 7))
lr = 3e-2  # 学习率
x,y
for i in range(epoch):
    y_hat = conv2d(x)
    l = (y_hat - y)**2
    conv2d.zero_grad()  #清空之前的梯度
    print(l)
    print("*"*10)
    print(l.sum())
    l.sum().backward()  #反向传播求导，因为backward求导要求对象时标量，所以需要先sum
    conv2d.weight.data[:] -= lr* conv2d.weight.grad
    if (i + 1) % 2 == 0:
        print(f'epoch {i+1}, loss {l.sum():.3f}')
print(conv2d.weight.data)

tensor([[[[0.0110, 0.0043, 0.0000, 0.0000, 0.0000, 0.0015, 0.0110],
          [0.0110, 0.0043, 0.0000, 0.0000, 0.0000, 0.0015, 0.0110],
          [0.0110, 0.0043, 0.0000, 0.0000, 0.0000, 0.0015, 0.0110],
          [0.0110, 0.0043, 0.0000, 0.0000, 0.0000, 0.0015, 0.0110],
          [0.0110, 0.0043, 0.0000, 0.0000, 0.0000, 0.0015, 0.0110],
          [0.0110, 0.0043, 0.0000, 0.0000, 0.0000, 0.0015, 0.0110]]]],
       grad_fn=<PowBackward0>)
**********
tensor(0.1666, grad_fn=<SumBackward0>)
tensor([[[[0.0070, 0.0011, 0.0000, 0.0000, 0.0000, 0.0025, 0.0070],
          [0.0070, 0.0011, 0.0000, 0.0000, 0.0000, 0.0025, 0.0070],
          [0.0070, 0.0011, 0.0000, 0.0000, 0.0000, 0.0025, 0.0070],
          [0.0070, 0.0011, 0.0000, 0.0000, 0.0000, 0.0025, 0.0070],
          [0.0070, 0.0011, 0.0000, 0.0000, 0.0000, 0.0025, 0.0070],
          [0.0070, 0.0011, 0.0000, 0.0000, 0.0000, 0.0025, 0.0070]]]],
       grad_fn=<PowBackward0>)
**********
tensor(0.1061, grad_fn=<SumBackward0>)
epoch 2, loss 0.