In [63]:
import numpy as py 
import torch
from torch import nn
import torch.utils.data as Data
from d2l import torch as d2l

true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [64]:
batch_size = 10
def load_array(data_arrays,batch_size, is_train=True):
    dataset = Data.TensorDataset(*data_arrays)
    return Data.DataLoader(dataset,batch_size,shuffle=is_train)

data_iter = load_array((features,labels),batch_size)
next(iter(data_iter))

[tensor([[ 1.2494, -0.8075],
         [ 0.1326,  2.1115],
         [ 0.6157, -1.1403],
         [ 0.6212, -0.9380],
         [ 0.2583,  0.1616],
         [ 1.6680, -0.3092],
         [-1.6012,  0.7630],
         [-0.1643,  0.9724],
         [ 0.1513, -0.4553],
         [-0.1193, -0.7953]]),
 tensor([[ 9.4381],
         [-2.7330],
         [ 9.3262],
         [ 8.6238],
         [ 4.1649],
         [ 8.5757],
         [-1.6047],
         [ 0.5618],
         [ 6.0559],
         [ 6.6602]])]

In [65]:
net = nn.Sequential(nn.Linear(2,1))
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)
for x in net.parameters():
    print(x)

Parameter containing:
tensor([[-0.0086, -0.0047]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)


In [66]:
loss = nn.MSELoss()
trainer = torch.optim.SGD(net.parameters(),lr=0.03)
#传入参数的初始值，后续通过调用step函数来更新参数

In [67]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000220
epoch 2, loss 0.000101
epoch 3, loss 0.000101
