In [1]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [2]:
x.requires_grad_(True)
x.grad


y = 2*torch.dot(x,x)
y

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4*x

tensor([True, True, True, True])

In [8]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad


tensor([2., 2., 2., 2.])

In [11]:
x.grad.zero_()
y = x * x
u = y.detach()  # 只保留变量，但是不具有grad,相当于常数，如果使用detach()_则会让y本身也失去grad
y,u
z = u*x
z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

In [14]:
x.grad.zero_()
y.sum().backward()
x.grad

tensor(14., grad_fn=<SumBackward0>)

In [19]:
def f(a):
    b = a*2
    while b.norm() <1000:
        b=b*2
    print(b)
    if b.sum()>0:
        c = b
    else :
        c = 100*b
    print(c)
    return c

a = torch.randn(size=(), requires_grad=True)
print(a)
d = f(a)
d.backward()

a.grad
     

tensor(0.7102, requires_grad=True)
tensor(1454.4176, grad_fn=<MulBackward0>)
tensor(1454.4176, grad_fn=<MulBackward0>)


tensor(2048.)