In [1]:
import torch
from torch import nn
from d2l import torch as d2l

In [3]:
n_train = 50  # 训练样本数
x_train, idx = torch.sort(torch.rand(n_train) * 5)   # 排序后的训练样本


(tensor([0.0253, 0.0367, 0.1280, 0.2253, 0.3222, 0.3795, 0.4000, 0.4643, 0.6481,
         0.7931, 0.9149, 1.1079, 1.1466, 1.1898, 1.2689, 1.2805, 1.3110, 1.4620,
         1.5031, 1.5407, 1.6506, 1.7624, 2.0068, 2.0937, 2.2969, 2.3732, 2.3815,
         2.4194, 2.4300, 2.6284, 2.6801, 2.7131, 2.7236, 2.7436, 3.4003, 3.4749,
         3.5081, 3.6291, 3.7728, 3.7941, 3.9971, 4.0758, 4.1005, 4.3960, 4.4660,
         4.4901, 4.6892, 4.7012, 4.7611, 4.7614]),
 tensor([46,  7, 40, 30, 44, 31,  4,  3, 12, 11, 36, 23, 22, 27, 43, 33, 39, 25,
         47, 41, 26, 35, 49, 28, 34, 20, 48, 16, 15,  2, 19, 45, 14,  9,  1, 38,
         13,  5, 37, 29,  8, 32, 17, 18,  6, 10,  0, 24, 42, 21]))

In [4]:
def f(x):
    return 2 * torch.sin(x) + x**0.8

y_train = f(x_train) + torch.normal(0.0, 0.5, (n_train,))  # 训练样本的输出
x_test = torch.arange(0, 5, 0.1)  # 测试样本
y_truth = f(x_test)  # 测试样本的真实输出
n_test = len(x_test)  # 测试样本数
n_test

50

In [5]:
def plot_kernel_reg(y_hat):
    d2l.plot(x_test, [y_truth, y_hat], 'x', 'y', legend=['Truth', 'Pred'],
             xlim=[0, 5], ylim=[-1, 5])
    d2l.plt.plot(x_train, y_train, 'o', alpha=0.5);

In [12]:
# X_repeat的形状:(n_test,n_train),
# 每一行都包含着相同的测试输入（例如：同样的查询）
X_repeat = x_test.repeat_interleave(n_train).reshape((-1, n_train))
X_repeat

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.1000, 0.1000, 0.1000,  ..., 0.1000, 0.1000, 0.1000],
        [0.2000, 0.2000, 0.2000,  ..., 0.2000, 0.2000, 0.2000],
        ...,
        [4.7000, 4.7000, 4.7000,  ..., 4.7000, 4.7000, 4.7000],
        [4.8000, 4.8000, 4.8000,  ..., 4.8000, 4.8000, 4.8000],
        [4.9000, 4.9000, 4.9000,  ..., 4.9000, 4.9000, 4.9000]])